language: cpp
compiler: g++

matrix:
  include:
    - os: osx
      osx_image: xcode9.2
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

before_install:
    - eval "${MATRIX_EVAL}"
    - brew update && brew upgrade boost
